[package]
name = "axum-sqlx"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true }
eyre = {workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
